services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://rentaro-m-b:6p7FA6REW27VbitX@postgres:5432/ai-model-exam-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: 'postgres:16.3-alpine'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '54342:5432/tcp'
    volumes:
      - 'pg_data:/var/lib/postgresql/data:delegated'
    healthcheck:
      test: ["CMD-SHELL", "su", "postgres", "-c", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
