// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: book.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (id, title, author, publisher, price)
    VALUES (nextval('BOOK_ID_SEQ'), $1, $2, $3, $4)
    RETURNING id, title, author, publisher, price
`

type CreateBookParams struct {
	Title     pgtype.Text
	Author    pgtype.Text
	Publisher pgtype.Text
	Price     pgtype.Int4
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.Publisher,
		arg.Price,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Publisher,
		&i.Price,
	)
	return i, err
}

const deleteBookByID = `-- name: DeleteBookByID :exec
DELETE
    FROM books
    WHERE id = $1
`

func (q *Queries) DeleteBookByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBookByID, id)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, author, publisher, price
    FROM books
    WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Publisher,
		&i.Price,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, publisher, price
    FROM books
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Publisher,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
